[package]
authors.workspace     = true
description.workspace = true
edition.workspace     = true
homepage.workspace    = true
keywords.workspace    = true
license.workspace     = true
name                  = "swc_ast_viewer"
readme.workspace      = true
repository.workspace  = true
version.workspace     = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
serde = "1.0.195"
serde-wasm-bindgen = "0.6.1"
serde_json = "1.0.108"
swc_core = { workspace = true, features = [
    "ecma_ast",
    "ecma_parser",
    "common",
    "ecma_visit",
    "ecma_transforms",

] }
swc_error_reporters = { workspace = true }
wasm-bindgen = "0.2.89"

[lib]
crate-type = ["cdylib", "rlib"]
