name: Test

on:
  push:
    branches:
      - "*"
  pull_request:
    types: ["opened", "reopened", "synchronize"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        name: Install Node
        with:
          node-version-file: ".node-version"

      - uses: pnpm/action-setup@v2
        with:
          run_install: |
            - args: [--frozen-lockfile, --strict-peer-dependencies]

      - run: pnpm run /check/
